### ISSUE TITLE
Able to enter negative numbers

### ISSUE THREAD

**Issue by Racoon11** [CaseyJohnson-RS/Electrician#1]
Steps that produced the error:
1. 
![image](https://github.com/CaseyJohnson-RS/Electrician/assets/67052706/99c3f8f4-ad50-40d3-a91f-1a7338a7b3c2)
2.
![image](https://github.com/CaseyJohnson-RS/Electrician/assets/67052706/b8366552-6b26-41a4-a39a-3fa7dd36436b)

Expected output: not able to add appliance with negative power consumption. Instead a appliance  with 0 power consumption is being added.

**Comment by CaseyJohnson-RS** [comment]
Thank you for help! I've fixed the bug. Now everything works correctly. 
![image](https://github.com/CaseyJohnson-RS/Electrician/assets/66686838/3721d626-a8fe-4b33-b780-450648913907)
