### ISSUE TITLE
PC shows incorrect value

### ISSUE THREAD

**Issue by Racoon11** [CaseyJohnson-RS/Electrician#2]
Steps that reproduce the problem:
1. Try to add a new Heater with some power
![image](https://github.com/Racoon11/OurProject/assets/67052706/6c23b8d8-ea1c-4011-9136-76fe08e5d5c7)

2. Power of the Heater shows incorrect value
![image](https://github.com/Racoon11/OurProject/assets/67052706/83ba5529-5c14-479a-aa6f-cdf7985616e5)

**Comment by CaseyJohnson-RS** [comment]
Thank u!!

**Comment by CaseyJohnson-RS** [comment]
Now it works correctly
![image](https://github.com/CaseyJohnson-RS/Electrician/assets/66686838/34054335-a326-40a6-80d2-439bc2531e2c)
![image](https://github.com/CaseyJohnson-RS/Electrician/assets/66686838/31065c50-4b1e-436a-8991-85ffa8c8cc12)
